### ISSUE TITLE
Font size, number of lines and start position constraints must always be sensible

### ISSUE THREAD

**Issue by angrave** [scribear/ScribeAR.github.io#152]
When the fontsize and number of lines are set at the maximum the start position can become negative and large (e.g. -48).

Suggestion:
Calculate the unused space. (which should never be negative).
The start position would work best if it is a percentage of the unused space, then it is always 0 - 100

If the fontsize * number of lines > available space then changing one should reduce the other so it still fits in the available space.
But how will you handle window resizing.?My suggestion: Keep track of actual number of lines possible vs desired number of lines.

**Comment by yuxuanjerrychen01** [comment]
Fixed in #157, merged
