### ISSUE TITLE
Menu buttons move depending on text in between

### ISSUE THREAD

**Issue by timurjavid** [scribear/ScribeAR.github.io#22]
![menu](https://user-images.githubusercontent.com/16829159/97482640-67726780-1924-11eb-861b-7756e849ca02.gif)

The back/forward buttons should stay static to allow users to page through the menus without having to move the mouse.

**Comment by yighax** [comment]
Hi. I would like to give it a try.

**Comment by coolhands25** [comment]
Latest version has a different menu structure.
