### ISSUE TITLE
Split reducers into component reducers

### ISSUE THREAD

**Issue by timurjavid** [scribear/ScribeAR.github.io#28]
Currently, all of our reducers are located in one large file and are combined in that file. We should split these reducers into component reducers and store them in the component folders that they belong to. This should make our structure a little more modular, since we would only need to add import statements when we create new components.

![reducers](https://user-images.githubusercontent.com/16829159/97488205-ecad4a80-192b-11eb-86a7-8e45e2d1fa44.png)

**Comment by harsh183** [comment]
Redux has its own reducer hooks I highly recommend as well.

**Comment by timurjavid** [comment]
Fixed with refactor
