### ISSUE TITLE
"Caption Size" Option -> Draggable pane

### ISSUE THREAD

**Issue by timurjavid** [scribear/ScribeAR.github.io#30]
![size](https://user-images.githubusercontent.com/16829159/99319494-3bfde100-282f-11eb-8dd7-bcba38f98fe0.png)

We can replace the "Caption Size" option menu to a more intuitive draggable interface for the captions that will shrink the visualizations as needed.

![drag](https://user-images.githubusercontent.com/16829159/99319435-1ec91280-282f-11eb-9adb-5f571d941ef2.gif)

There's an NPM package that contains a ready made widget for this:

https://www.npmjs.com/package/react-resizable

**Comment by Jiaming1999** [comment]
I will try the package, draggable zone indeed looks messy rn

**Comment by coolhands25** [comment]
No longer applicable to current version.
