### ISSUE TITLE
Streamtext integration

### ISSUE THREAD

**Issue by timurjavid** [scribear/ScribeAR.github.io#31]
Integrating the streamtext captioning service into our application.

https://streamtext.net/demo/

**Comment by coolhands25** [comment]
Use this API: https://support.streamtext.net/hc/en-us/articles/4633531262989-Realtime-Caption-Pull-API-for-configurable-realtime-JSON-caption-pull-from-ST

Alternative API (likely not ideal for us): https://support.streamtext.net/hc/en-us/articles/360045245951-Real-Time-Caption-Ingestion-API-for-posting-captions-to-a-URL

**Comment by jmkl009** [comment]
Hi, I have coded a primitive integration, but I don't have permission to push code. If possible, I would like to kindly ask for a collaborator role for the project.

**Comment by angrave** [comment]
Please check your email /github for an invite request to the developer's team.

**Comment by jmkl009** [comment]
> @jmkl009 Please check your email /github for an invite request to the developer's team.

PR submitted #183

**Comment by coolhands25** [comment]
Implemented
