### ISSUE TITLE
Fix webspeech for now

### ISSUE THREAD

**Issue by Jiaming1999** [scribear/ScribeAR.github.io#35]
By replacing the whole Captions folder, the previous Captions folder now named CaptionsNew, we need to find out what's wrong with that folder.

**Comment by timurjavid** [comment]
Temporary revert to old captions by pushing f4a0e93. Possibly broken with aebba34f524a8d84be9e7f1299f137fc030c230f by @WilliamFoster3.

**Comment by timurjavid** [comment]
Duplicate as issue #34. Adding update comment to #34.
