### ISSUE TITLE
Menu buttons should stay static as you scroll 

### ISSUE THREAD

**Issue by timurjavid** [scribear/ScribeAR.github.io#36]
The top of the menu ( < Main Menu > <) should stay static when scrolling so the user doesn't get lost in the menus.

![menutop](https://user-images.githubusercontent.com/16829159/100285259-2f1b7480-2f36-11eb-8c91-f6c5c9d1a878.gif)

**Comment by Jiaming1999** [comment]
Now the header navi is fixed, some bugs with style tho
