### ISSUE TITLE
Default visualization location change

### ISSUE THREAD

**Issue by timurjavid** [scribear/ScribeAR.github.io#40]
Right now, the audio visualization is defaulted to be at the very left of the screen. This hides the circular visualization under the menu, making the user wonder if the visualization works. If we move the visualization to the middle or the right by default, we can eliminate this confusion.

![visualizationbehindmenu](https://user-images.githubusercontent.com/16829159/100932413-7616e600-34b1-11eb-9048-96a6d08e42d1.gif)

**Comment by Jiaming1999** [comment]
Now it should appear a little bit right side so you can see it with menu open
