### ISSUE TITLE
Ability to auto hide or remove header

### ISSUE THREAD

**Issue by harsh183** [scribear/ScribeAR.github.io#61]
Once I set up the captioning service I usually inspect element and delete the `<head>` node when I'm watching lecture because it's blue and stands out. Maybe it can be visible on mouse hover (might make it less accessible) or have a keyboard shortcut to make it visible. 

I think the top bar should be hidden as much as possible.

**Comment by coolhands25** [comment]
This feature is present in the latest version.

**Comment by harsh183** [comment]
Awesome! Great to see
