### ISSUE TITLE
Add documentation/blog post comparing different types of mics

### ISSUE THREAD

**Issue by harsh183** [scribear/ScribeAR.github.io#67]
So far I've tried different type of microphones and we can document this somewhere for people. Here have been my experiences so far:

## Lapel Mic

Pros: 
* Picks up the professor's voice pretty well
* Small form factor
Cons:
* The professor often has to wear multiple mics now.
* Requires the professor to do some work too. 
* The professor has to make sure the mic is on.
* Has a usb connector dongle (instead of using something like bluetooth)
* Slightly fragile

## Laptop Mic 

Pros:
* Doesn't cost anything.
* No setup
* Picks up both professor as well students around.
Cons:
* Bad sound quality (-> meh captions)

## Ommidirectional mic

(I tried one lecture with Colin's mic, not sure what model it is but it's in reference to that)

Pros:
* Picked up a lot of the professor talking 
* Picked up a good amount of other students
* Bluetooth wireless so I can sit anywhere
Cons:
* Not as good as lapel mic on professor
* Huge form factor, doesn't even fit in my bag so I have to carry it briefcase style
* Takes 5-10 minutes to set up before lecture start
* Sometimes unsure if connected correctly. Colin recommended putting it on mute to check and it worked but I had to go back and forth a lot.
* Expensive

**Comment by ammpr** [comment]
Resolved.
