### ISSUE TITLE
Pure black background for Moverio

### ISSUE THREAD

**Issue by harsh183** [scribear/ScribeAR.github.io#71]
For normal screens, having a `#000000` bg color is too stark, but for Moverio the black turns into transparent. This is useful for seeing what's going on since the current background is _slightly_ visible.

**Comment by timurjavid** [comment]
Themes with pure black background were added in version 7. They are the top line of the themes menu.
![Screenshot from 2021-11-29 17-49-42](https://user-images.githubusercontent.com/16829159/143960657-ae4ce61c-9ce1-41d3-a942-917cc9278520.png)

related #89
.
